language: php
sudo: false
dist: trusty

matrix:
  include:
    - php: nightly
      env:
        - WP_VERSION=latest
        - CC_TEST_REPORTER_ID=62ea428024560852130fdce61b1b1f8753028c8c6c6a3ef71a3c8deb77ba887f
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

    - php: 7.1
      env:
        - WP_VERSION=latest
        - CC_TEST_REPORTER_ID=62ea428024560852130fdce61b1b1f8753028c8c6c6a3ef71a3c8deb77ba887f
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=3.8
    # Remove 5.3 or Travis build becomes too large.
    # - php: 7.1
    #   env: WP_VERSION=latest SWITCH_TO_PHP=5.3
    # - php: 7.1
    #   env: WP_VERSION=3.8 SWITCH_TO_PHP=5.3
    - php: 7.1
      env: WP_VERSION=latest SWITCH_TO_PHP=5.2
    - php: 7.1
      env: WP_VERSION=3.8 SWITCH_TO_PHP=5.2
    - php: 5.4
      env: WP_VERSION=latest
    - php: 5.4
      env: WP_VERSION=3.8
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=3.8
      php: nightly
    - env: WP_VERSION=3.8
      php: 7.1
    - env: WP_VERSION=latest
      php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.phpbrew

before_script: # Make PHP 7 test work. https://github.com/CMB2/CMB2/pull/885
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      set -e
      bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      source tests/bin/install-php-phpunit.sh
      set +e
    fi
  - |
    if [[ ! -z "$CC_TEST_REPORTER_ID" ]] ; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi
  - phpunit --version
  - php -i | grep xdebug

script: if [[ latest == $WP_VERSION ]]; then phpunit --coverage-clover=clover.xml; else phpunit --exclude-group cmb2-rest-api --coverage-clover=clover.xml; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if [[ ! -z "$CC_TEST_REPORTER_ID" ]] ; then
        ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT;
      fi
    fi

branches:
  only:
  - master
  - trunk

notifications:
  slack:
    rooms:
      - secure: g3L0XaiaUjUeBoNMLXx4pdz+7JudZhFGPY1mOX1WkC4B0zo+M/tGdhLLz/
    on_success: never
    on_failure: change
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/00b1df026574cdaeb815
    on_success: never  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
  email:
    on_success: never # default: change
    on_failure: change # default: always
